### ISSUE TITLE
csv object is not a function

### ISSUE THREAD

**Issue by Banack** [ithinkdancan/node-semrush#2]
Every time I call node-semrush I get this error:

user@sky:~/htdocs/***# node test_semrush.js

/***/node_modules/node-semrush/index.js:77
                                                csv().from.string(urldata, {delimiter: ';', columns: true}).to.array(funct
                                                ^
TypeError: Cannot call method 'string' of undefined
    at IncomingMessage.<anonymous> (/***/node_modules/node-semrush/index.js:77:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by edravis** [comment]
npm install csv 

maybe?

**Comment by edravis** [comment]
same issue here

**Comment by Banack** [comment]
After reviewing the node-semrush code I've understand that csv has changed, so
you need to deal with a strict csv version: 0.2.9

Please add to your package.json:

  "dependencies": {
		"csv": "0.2.9"
	}

**Comment by Banack** [comment]
unfortunatly is not enought.
You need csv 0.2.9
not the current one

2015-01-28 17:45 GMT+01:00 Rubén Sospedra <notifications@github.com>:

**Comment by edravis** [comment]
I solved, preparing a pull request. Briefing: csv npm module splitted into 4. Now, semrush needs csv-parse and a modification at index.js:77

**Comment by edravis** [comment]
@Banack  it's fixed, just update the lib and @ithinkdancan I think we can close this.
